import '/imports/startup/server/Accounts';
import '/imports/startup/server/Publications';
import '/imports/startup/server/Mongo';
import '../imports/api/userInfo/UserInfoCollection.methods';
import '../imports/api/cars/CarsCollection.methods';
import '../imports/api/userInfo/UserInfoCarCollection.methods';
import '../imports/api/emissions/TripsCollection.methods';
import '../imports/api/emissions/EmissionsCollection.methods';
import '../imports/startup/both/Methods';
